### ISSUE TITLE
Proper app and repo name

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/files_videoplayer#26]
the app name is not allowed to contain a -

suggested names:
- [ ] files_videojs
- [ ] files_video
- [x] files_video_player

**Comment by DeepDiver1975** [comment]
@nickvergessen @karlitschek @jancborchardt

**Comment by nickvergessen** [comment]
files_video_player :+1:

**Comment by karlitschek** [comment]
ok. let's rename repo and app to files_video_player :+1:

**Comment by karlitschek** [comment]
@Instagit do you agree ?

**Comment by Instagit** [comment]
Yeah, sure it makes sense to give it a more general name. I'd name it files_videoplayer in accordance with the other repo names (files_texteditor, files_antivirus, files_pdfviewer), but files_video_player works, too :+1:

**Comment by PVince81** [comment]
"files_video_player" is a bit close to the old "files_videoviewer".

Why drop the fancy name ? :smile:

**Comment by DeepDiver1975** [comment]
so files_videoviewer then an remove the old code base https://github.com/owncloud/apps/tree/master/files_videoviewer ?

**Comment by nickvergessen** [comment]
No, please not app replacement again :-1:

**Comment by Instagit** [comment]
Didn't know using the old app name causes trouble. Just go with files_video_player then :)

**Comment by jancborchardt** [comment]
Simply `files_videos` please, or `files_videoplayer`. We have enough underscores. ;) And conflict with the old »videoviewer« doesn’t matter.

And yes, we should drop the strange fancy name.

**Comment by karlitschek** [comment]
no. no app replacement. It is a new and different app with a different name

**Comment by karlitschek** [comment]
Let's go then with files_videoplayer please. @DeepDiver1975 let me know when ready.

**Comment by DeepDiver1975** [comment]
> Let's go then with files_videoplayer please. @DeepDiver1975 let me know when ready.

done @karlitschek

**Comment by DeepDiver1975** [comment]
#27 has to be merged now

**Comment by karlitschek** [comment]
thanks. the build script is now updated and the nightly builds are regenerated

**Comment by jancborchardt** [comment]
Thanks!
