### ISSUE TITLE
Security check

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/files_videoplayer#28]
- [x] XSS in file `.replace` in `viewer.js` (https://github.com/owncloud/files_video_player/pull/29)
- [x] Get rid of SWF fallback. Too big of a security risk. (https://github.com/owncloud/files_video_player/pull/31)
- [x] Remove demos and stuff  (https://github.com/owncloud/files_video_player/pull/30)
- [x] Verify .JS files with upstream
- [x] Look into sandboxing the stuff… (let's look into this for 9.1)
- [x]  Remove unrequired files (https://github.com/owncloud/files_videoplayer/pull/32) 
- [x]  …

**Comment by LukasReschke** [comment]
The SWF fallback is a nightmare. Getting rid of it then :speak_no_evil: :hear_no_evil: :see_no_evil:

**Comment by Instagit** [comment]
I agree, but please be aware that IE8 support relies on flash: [Support for older browsers](https://github.com/owncloud/files_videoplayer/issues/12).

**Comment by LukasReschke** [comment]
Yup. Core has officially dropped IE 8 support for 9.0 though :)

**Comment by Instagit** [comment]
Nice :)

**Comment by LukasReschke** [comment]
Nice work @Instagit. I have finished checking this app and it has passed the security review. So we can ship this with 9.0 :rocket: 

If you ever have any questions with regard to security feel free to ping me here and I'll happily help.
