### ISSUE TITLE
CSS isn't loaded correctly in ownCloud 9 version of the player

### ISSUE THREAD

**Issue by Instagit** [owncloud/files_videoplayer#36]
The player looks like this:
![1](https://cloud.githubusercontent.com/assets/2681794/13632146/9516d154-e5e8-11e5-8c8a-323b7cda3c83.png)

It should look like this:
![2](https://cloud.githubusercontent.com/assets/2681794/13632157/97949a9c-e5e8-11e5-829d-65387200e2e0.png)

For some reason not all CSS is applied. When you install the old app (VideoJS Sublime) from the app menu, it works.

**Comment by Instagit** [comment]
It's because of [this change](https://github.com/owncloud/files_videoplayer/commit/8202948d8889835bf1cf9c2abad2960c1e832f19#diff-69dcd3388de794078e66154ddc0e27c6). 

````"techOrder": ["html5"]````

is causing the behaviour. Is there a reason this was added? Flash fallback was removed so I don't think we need this option.

**Comment by Instagit** [comment]
@DeepDiver1975

**Comment by Instagit** [comment]
https://github.com/owncloud/files_videoplayer/tree/css-fix

This should fix it.

**Comment by jancborchardt** [comment]
@Instagit can you open a pull request with that fix? We should then also backport this because otherwise it doesn’t blend in with ownCloud’s nice design. cc @karlitschek

**Comment by jancborchardt** [comment]
@LukasReschke you added this attribute with https://github.com/owncloud/files_videoplayer/commit/73dff418b43786a150427d143a9600f6d7fd39e9 – any specific reason for that?

**Comment by LukasReschke** [comment]
> @LukasReschke you added this attribute with 73dff41 – any specific reason for that?

Basically to disable the Flash fallback completely as per http://stackoverflow.com/questions/15508563/disable-flash-in-video-js

Changing it back won't be terrible bad as it is not used in newer browsers anyways. But I really wonder why this has an effect on the CSS. This seems pretty strange :confused:

**Comment by Instagit** [comment]
It causes an error not directly with the CSS, but with the VideoJS initialization and that affects the entire element. HTML classes are missing etc.

````
SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data
````

I think it's actually just a syntax error, data-setup needs single quotes. We can let it in and fix it that way.

**Comment by karlitschek** [comment]
backport is fine with me because I assume that is is very limited and simple.

**Comment by jancborchardt** [comment]
@Instagit thanks for the good catch! And sorry for not having that with ownCloud 9, but the patch release will be all the more awesome. :)
