### ISSUE TITLE
enhancement: support .mkv-files

### ISSUE THREAD

**Issue by BenS89** [owncloud/files_videoplayer#43]
The new video player app in ownCloud 9 is really cool! It would be great if it also could support mkv-videos. Is this on the roadmap?

Thanks and best regards
Ben

**Comment by Instagit** [comment]
Playing MKV videos with HTML5 would depend on the browser support and right now browsers don't support it.

We could try some trickery with the MIME type that could make MKV playable under certain conditions, but it wouldn't be a good, reliable solution.
