### ISSUE TITLE
Videos in shared folders could not be played

### ISSUE THREAD

**Issue by kriztan** [owncloud/files_videoplayer#45]
Hi, i've a problem with OC 9 and a shared folder which contains videos. The MP4 files could not be played with the video player, images inside this folder where displayed correctly.
I've tested it with Chrome on a Windows 7 mashine. The videos could be played after logging in, but not when they are insinde a shared folder.

**Comment by timmmmmey** [comment]
Same here. 9.0.1 stable

**Comment by Instagit** [comment]
Could you make a screenshot that shows the problem?

**Comment by timmmmmey** [comment]
For sure. Javascript Console doens't show any errors in chrome. 
![github](https://cloud.githubusercontent.com/assets/11060828/14598592/51c1e4ea-0553-11e6-9b80-827f8caeb62c.png)

**Comment by Instagit** [comment]
I can reproduce the problem now with Chrome on Windows 7, but only for some videos.

What I can say so far is that when the error occurs, the browser gets two replies from the server for the video instead of only one.

Thanks for the report, we're looking into this and I think playing videos directly from shared folders is generally still being worked on.

**Comment by timmmmmey** [comment]
I can reproduce it on:
Windows 10 x64, Chrome (current)
Android  5.1, Chrome (current)
Fedora x64, Chrome (current), Firefox (stable) is working (!)

And yes, the problems occours only on a few files, I grabbed some examples and it seems no codec problem. The following 4 files were tested and were working as logged in user. With a shared link as a guest, only two files were working. And File 2 and 4 had the same codec (source: avprobe)

Not working:
- Stream #0.0(eng): Video: h264 (Constrained Baseline), yuv420p, 408x720, 676 kb/s, 30 fps, 30 tbn, 60 tbc (default), Stream #0.1(eng): Audio: aac, 48000 Hz, mono, fltp, 95 kb/s (default)
- Stream #0.0(und): Video: h264 (Main), yuv420p, 640x360, 703 kb/s, 30 fps, 19200 tbn (default), Stream #0.1(und): Audio: aac, 44100 Hz, stereo, fltp, 62 kb/s (default)

Working:
- Stream #0.0(und): Video: h264 (Constrained Baseline), yuv420p, 212x320, 43 kb/s, 15 fps, 15360 tbn, 30 tbc (default), Stream #0.1(und): Audio: aac, 22050 Hz, mono, fltp, 36 kb/s (default)
- Stream #0.0(und): Video: h264 (Main), yuv420p, 640x360, 687 kb/s, 30 fps, 19200 tbn (default)
    Stream #0.1(und): Audio: aac, 44100 Hz, stereo, fltp, 59 kb/s (default)

**Comment by Instagit** [comment]
For some files, the server streams the data (works) and for others, it sends everything at once (doesn't work). I need someone who knows more about the video handling, but that seems to be the problem.

@LukasReschke @jancborchardt

**Comment by jancborchardt** [comment]
cc @owncloud/javascript @DeepDiver1975 any idea here?

**Comment by PVince81** [comment]
@timmmmmey is this only for shared files or does it also happen for non-shared ones ?

Regarding codecs, some codecs might require to seek to the end of the file to get important information. I suppose the video player should then do a Range request to the end of the file for that. Range requests should work.

Please check the network console for the working vs non-working files, maybe there's a difference in the HTTP requests that could pinpoint whether there's an issue on the server, possibly with range requests.

**Comment by timmmmmey** [comment]
@PVince81 All the 4 files are working, if I login and use the gui to find the path. If I use the shared-link, then 2 are not working. 
As @Instagit already pointed out, the not-working videos have 2 download requests.

Not working:
![notworking](https://cloud.githubusercontent.com/assets/11060828/14632046/caae3e62-0616-11e6-8a34-b1a8f3c6eaf9.png)
Working:
![working](https://cloud.githubusercontent.com/assets/11060828/14632047/cab3f5c8-0616-11e6-9898-9f1643f5f369.png)

**Comment by PVince81** [comment]
Can you pick one video that works in regular mode and breaks in public mode. Then check the "Range" header in the network console.

I suspect that in publicpreview mode the Range request doesn't work properly.

**Comment by PVince81** [comment]
The call in question is likely to be the one with "download?..."

**Comment by PVince81** [comment]
At first I'd have said the video player needs to be adjusted to use the public Webdav URL instead, which supports Range requests. However, this endpoint has some issues in some browsers due to the fact that it requires either a username to be passed in the URL or an "Authorization" header to be set, and both aren't supported by the video API.

See https://github.com/owncloud/core/issues/21787#issuecomment-211803540

**Comment by timmmmmey** [comment]
Okay, that looks strange
First call: Range:bytes=0-
Second call: Range:bytes=48-2341567

**Comment by timmmmmey** [comment]
And for a video thats works in a shared link:
First (and only) call: Range:bytes=0-585642

**Comment by lenz1111** [comment]
This is due to an unsupported http range requests. Temporary solution (tested on 9.0.1) - that add support for this:
[owncloud9_download_http_range.zip](https://github.com/owncloud/files_videoplayer/files/240335/owncloud9_download_http_range.zip)

**Comment by jancborchardt** [comment]
@lenz1111 if that fixes it, can you open a pull request to this repository please? :) If you need any help, you can ask. Or you are welcome in our IRC channel #owncloud-dev on freenode IRC.

**Comment by PVince81** [comment]
I had a look t the patch already and might need a bit of tweaking, but best to discuss this in a PR.
Thanks.

**Comment by lenz1111** [comment]
Opened a pull request with my modifications https://github.com/owncloud/core/pull/24354
Pull request is for core module (not files_videoplayer)

**Comment by jancborchardt** [comment]
@lenz1111 aaawesome! Welcome to the ownCloud community! :)

**Comment by PVince81** [comment]
Due to a little rebase incident, the PR has moved here: https://github.com/owncloud/core/pull/24750 :smile:

**Comment by PVince81** [comment]
Please try again with 9.0.3RC1, public share range requests were implemented there
