### ISSUE TITLE
Files mp4 and flv are not reproduced in files_videoplayer

### ISSUE THREAD

**Issue by davitol** [owncloud/files_videoplayer#47]
### Steps to reproduce

1. Upload a .flv and .mp4 file
2. Try to reproduce them

### Expected behaviour

The videos should be reproduced

### Actual behaviour

The videos are not reproduced:
- .flv file: video could not be opened because the type is not supported...
- .mp4 file  does not reproduce the images but sound was ok in Chrome. In other browser it did not work at all.

Note: With  files_videoviewer app it went fine

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version: "9.1.0.0","versionstring":"9.1.0 pre alpha","edition":"Enterprise"}

### Logs

```
```

**Updated from an older ownCloud or fresh install:** Fresh install

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox and Chrome for Mac OSX.
Edge

**Comment by Instagit** [comment]
It seems the videoviewer app uses Flash and Silverlight plugins. It's possible that these plugins support different formats than regular browsers with HTML5.

I have seen the problems you described before and it was because the browser didn't support the video format. There's not much we can do about that.

Could you give the exact codec information of the videos you tried to play?

**Comment by davitol** [comment]
@Instagit 
For the flv file:
![screen shot 2016-05-11 at 12 28 35](https://cloud.githubusercontent.com/assets/10596560/15178115/17432bd4-1774-11e6-8a29-0f7d05fd0a45.png)

For the mp4 file:
![screen shot 2016-05-11 at 12 30 42](https://cloud.githubusercontent.com/assets/10596560/15178147/3a61e9a2-1774-11e6-8236-73e6781717fb.png)

**Comment by Instagit** [comment]
Like I said, FLV definitely won't work without plugins, because browsers don't support the container format.

For the MP4 I need more info. It's probably because of the encoding profile that is not supported. Do you have ffmpeg or another program that can show detailed information?

`ffmpeg -i FILENAME`

**Comment by davitol** [comment]
ffmpeg -i videoFile.MP4
ffmpeg version 2.6.2 Copyright (c) 2000-2015 the FFmpeg developers
  built with Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.6.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-vda
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'videoFile.MP4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: mp41
    creation_time   : 1970-01-01 00:00:00
  Duration: 00:04:40.24, start: 0.000000, bitrate: 220 kb/s
    Stream #0:0(und): Video: mpeg4 (Simple Profile) (mp4v / 0x7634706D), yuv420p, 320x240 [SAR 1:1 DAR 4:3], 152 kb/s, 20 fps, 20 tbr, 20 tbn, 20 tbc (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 64 kb/s (default)
    Metadata:
      creation_time   : 1970-01-01 00:00:00
      handler_name    : SoundHandler

**Comment by Instagit** [comment]
It's because of

`mpeg4 (Simple Profile)`

If you try to drag the video from your hard drive into Firefox, it will say the file is corrupted. That's because Firefox doesn't support all features required to play the video. There's no easy way for us to fix that.

I think making more video formats playable is being discussed and there are several ways to do it, but each of them has drawbacks.

**Comment by davitol** [comment]
@carlaschroder Maybe it should be good to document which extensions are supported by files_videoplayer

**Comment by Instagit** [comment]
You can find a list of supported media formats for browsers [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility).

**Comment by carlaschroder** [comment]
@davitol If I had a clue what they are.  Maybe someday we can have comments in code, and useful Github READMEs.

**Comment by Instagit** [comment]
The player simply plays all files that the browser can play. What exactly those formats are isn't information that belongs in code comments or the readme for this player as it's subject to changes and already well documented for the browsers themselves.

**Comment by carlaschroder** [comment]
I'd say that sort of information absolutely belongs in a code comment or readme, as it's essential to understanding how it operates. Thanks for the link; I'll update the docs.

**Comment by RealRancor** [comment]
Agree, that could be useful to document. Have tons of questions about "hey, my video is not playing" at the forums and no one there has a real knowledge about this to be able to answer / support such issues.

**Comment by Instagit** [comment]
So I think this can be closed as it's not an issue with the player?

**Comment by davitol** [comment]
@Instagit Completely agree. Let's close it and thank you for all the info provided 🍻
