### ISSUE TITLE
Rotated movies on the "share file" page

### ISSUE THREAD

**Issue by FredrikLindseth** [owncloud/files_videoplayer#54]
I captured a video with my phone. Transferred it to my PC and uploaded it to OC. The movie is in an MP4 container and captured with Snapchat on Android.
When the movie is shown on my PC and phone it's shown in vertical/upright mode, as it was filmed. But when shown via the "share file"-link in Owncloud the movie is show in the horizontal mode, i.e. rotated sideways.

This happens on Mozilla Firefox 47 on windows and Google Chrome 52.0.2743.116 m.
Microsoft Edge 25.10586.0.0 manages to rotate the movie the correct way.

The movie in question: https://oc.0v.no/s/ALeQ6FFFeSFdw2Q

**Comment by Instagit** [comment]
Hi,
your video has

````
Rotation : 90
````

in the metadata, so I think showing it rotated is correct behaviour. Playing it in VLC looks the same as on the share page to me.
