### ISSUE TITLE
H. 265

### ISSUE THREAD

**Issue by detelchen** [owncloud/files_videoplayer#58]
Is there any possibility to use the video player in nextcloud to watch h.265 videos?
I can download and then watch with vlc etc. but that is not cool.
I read something about an Javascript playayer libde265.js .
Is it possible to implement in nextcloud?

**Comment by Instagit** [comment]
The player is ready for any codec, it only depends on browser support. I don't think including libde265.js for decoding is a good idea, because it's experimental and the adoption of H.265 is very low anyway. This would be best implemented as an extension.

**Comment by detelchen** [comment]
Thank you.
So is there a browser spporting h.265 or x.265
Itried firefox and chrome. No luck

**Comment by Instagit** [comment]
I don't think any browser supports it and since there is a good, free alternative on the way (VP9) it's questionable if they want to go through the licensing trouble with H.265 again.

**Comment by detelchen** [comment]
switched on edge.
that seems to be ok
but with edge I cannot delete files in nextcloud 10
