### ISSUE TITLE
Show Timecode in Skin

### ISSUE THREAD

**Issue by tinogithub** [owncloud/files_videoplayer#59]
Hi there,
referring to issue #50 i'd like to display timecode of the video. Like the other options i.e. Speedrate etc. it would be nice to have access to these.

thank you

**Comment by claell** [comment]
Currently the video player is not pretty useful. It is too minimalistic.

**Comment by Instagit** [comment]
The minimalistic look was one of the reasons the player was introduced, as the former player was very overloaded and didn't fit with the rest of the UI. I agree that a timecode would be good to have though and will keep it in mind for future updates. Speedrate etc. (what do you mean by etc.?), not so much.

Video.js, the library we use, has support for skins, so if you find a good one that looks elegant and not too crowded, feel free to post it as the current skin doesn't work with the latest Video.js version anyway and will probably need to be replaced at some point.
