### ISSUE TITLE
Can't play video with "#" in path or filename

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/files_videoplayer#63]
### Steps to reproduce
1. Upload video.mp4 in web UI ==> plays well if I open in files app
2. Rename to #video.mp4 in web UI ==> Error: The video could not be loaded, either because the server or network failed or because the format is not supported.
3. Try #test/video.mp4 in web UI ==> Error: The video could not be loaded, either because the server or network failed or because the format is not supported.

### Expected behaviour
Every supported video file should be played.

### Actual behaviour
Error: The video could not be loaded, either because the server or network failed or because the format is not supported.

### Server configuration
**ownCloud version:** (see ownCloud admin page)
9.1.3

### Client configuration
**Browser:**
Chrome 55

**Operating system:**
Mac OS 10.12.1

#### Browser log
```
 DOMException: Failed to load because no supported source was found.
/index.php/apps/files/?dir=/testing/%23video&fileid=35235:1 Uncaught (in promise)
```

@DeepDiver1975 @butonic Who is the expert for this?

00007045

**Comment by michaelstingl** [comment]
Video play also well in share-link, and a user reported it worked in oC 8.

**Comment by DeepDiver1975** [comment]
this is a url encoding issue - I'll prepare a pr tomorrow
