### ISSUE TITLE
Generate/customize Open Graph meta data for videos

### ISSUE THREAD

**Issue by Vinnythetrue** [owncloud/files_videoplayer#68]
When I share a direct link to a video hosted on an OwnCloud server, for instance on Facebook, nothing appears in the share, except the url of the server... It would be awsome to get Owncloud to generate Open Graph Metadata for videos, including a thumbnail poster if possible, description etc.

Or maybe is this already possible by any means ?

**Comment by DeepDiver1975** [comment]
owncloud 10 implements open graph 

![bildschirmfoto von 2017-05-16 14-10-03](https://cloud.githubusercontent.com/assets/1005065/26105216/66659bde-3a41-11e7-9a36-6c2bd49de901.png)

![bildschirmfoto von 2017-05-16 14-10-40](https://cloud.githubusercontent.com/assets/1005065/26105239/7aea9668-3a41-11e7-81d9-a88131000b57.png)

**Comment by Vinnythetrue** [comment]
That seams like a great answer !

So I just upgraded to 10.0.0 to check this out. But when I share an mp4 video over to facebook, I get a standard "Owncloud - web services under your control" title and generic description as well as the owncloud logo as a preview... Is it possible to customize the title/description and image as well ?

**Comment by DeepDiver1975** [comment]
if preview generation for video is enabled and properly configured - yes ... let me test this .... 😉

**Comment by Vinnythetrue** [comment]
Couldn't find these parameters... Where should I look ? I may try myself, be glad too, even :)

**Comment by DeepDiver1975** [comment]
maybe this helps: https://doc.owncloud.org/server/10.0/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=preview#previews

for video previews ffmpeg has to be installed afaik ....
