### ISSUE TITLE
NC14.0.1 & files_videoplayer 1.3.0: "App is not compliant"

### ISSUE THREAD

**Issue by Sanookmakmak** [owncloud/files_videoplayer#75]
`occ app:check-code files_videoplayer`

```
Invalid appinfo.xml file found: Element 'description': This element is not expected. Expected is one of ( name, summary ).

App is not compliant
```

What does this mean?
Thank you!

**Comment by DeepDiver1975** [comment]
This app is for owncloud - not nextcloud. Please report there: https://github.com/nextcloud/files_videoplayer

**Comment by Sanookmakmak** [comment]
https://github.com/nextcloud/files_videoplayer/issues/64
