### ISSUE TITLE
Video player does not display time

### ISSUE THREAD

**Issue by voroyam** [owncloud/files_videoplayer#78]
### Steps to reproduce
1. Install oC 10.0.10 and files_video player
2. Upload a video and start playing the file / share file with local user
3. Share the video via public link

### Expected behavior
In both cases (2. and 3.) the file should play and in the bottom left corner the time should be displayed

![image](https://user-images.githubusercontent.com/24212810/47727586-f9273b80-dc5c-11e8-863d-7c178ed806c3.png)

### Actual behavior
after 2. time **is not** displayed (file is played by owner or shared with local user)

after 3. time **is** displayed ( files is shared via public link and played via public link)

**Comment by DeepDiver1975** [comment]
On the share page the browser native video playing capabilities are used. The video player is only used when being logged in. 

I agree that this is disgusting from a user experiance point of view. 
The solution at the end needs a closer look and partial redesign of the front end -> phoenix
