### ISSUE TITLE
视频格式

### ISSUE THREAD

**Issue by QiSunGitHub** [owncloud/files_videoplayer#81]
目前都支持那些视频格式的播放？
是否可以即成视频格式转换插件？如何集成？

**Comment by DeepDiver1975** [comment]
English please - THX

**Comment by QiSunGitHub** [comment]
What are the video formats that support online playback?

Is it possible to integrate video format conversion plug-ins? How?

**Comment by Instagit** [comment]
Hi QiSunGitHub.

Supported formats: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

Video conversion: Yes it's possible, but not easy to do. Please see discussions here:

https://github.com/nextcloud/files_videoplayer/issues/40
https://github.com/owncloud/gallery/issues/194
https://github.com/nextcloud/server/issues/604
